[package]
name = "bedrock_level"
version = "0.1.0"
edition = "2024"

[features]
deny-unknown-fields = []
default = ["deny-unknown-fields"]

[[bench]]
name = "subchunk"
harness = false

[[bench]]
name = "unpack"
harness = false

[dependencies]
rusty-leveldb = { git = "https://github.com/bedrock-crustaceans/leveldb-rs", rev = "5dd2ad5bf1db45d11dc11b62682a63687978ec53" }
miniz_oxide = { version = "0.9.0" }

bedrock_shared = { path = "../shared" }
nbtx = { workspace = true }

thiserror = { workspace = true }
serde = { workspace = true }
byteorder = { workspace = true }
bytemuck = { workspace = true }
smallvec = "1.15.1"
rustc-hash = "2.1.1"
nohash-hasher = "0.2.0"
paste.workspace = true
serde_repr.workspace = true

[dev-dependencies]
tar = { workspace = true }
flate2 = { workspace = true }
tempfile = { workspace = true }
criterion = { workspace = true }
