[package]
name = "bedrock_vanilla_data"
version = "0.1.0"
edition = "2024"

[features]
deny-unknown-fields = []
default = ["deny-unknown-fields"]

[dependencies]
bedrock_level = { path = "../level" }
nbtx = { workspace = true }

serde = { workspace = true }
serde_repr = { workspace = true }

[dev-dependencies]
tar = { workspace = true }
flate2 = { workspace = true }
tempfile = { workspace = true }
