[package]
name = "bedrock_shared"
version.workspace = true
edition.workspace = true

[dependencies]
bedrock_protocol_core = { path = "../protocol_core" }
bedrock_macros = { path = "../macros" }

tracing = { workspace = true }

byteorder = { workspace = true }
varint-rs = { workspace = true }
facet.workspace = true
