[package]
name = "bedrock_protocol_core"
version.workspace = true
edition.workspace = true

[dependencies]
nbtx.workspace = true
paste.workspace = true
seq-macro.workspace = true
byteorder.workspace = true
thiserror.workspace = true
uuid.workspace = true
strum.workspace = true

[features]
packet-meta = []
packet-dyn = []
packet-trace = []