[package]
name = "bedrockrs_network"
version = "0.1.0"
edition = "2024"

[dependencies]
bedrockrs_proto = { path = "../proto" }
bedrockrs_proto_core = { path = "../proto_core" }

tokio = { workspace = true }
byteorder = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }

raknet = { git = "https://github.com/bedrock-crustaceans/raknet-rs.git" }

