[package]
name = "bedrock_network"
version.workspace = true
edition.workspace = true

[dependencies]
bedrock_protocol = { path = "../protocol" }
bedrock_protocol_core = { path = "../protocol_core" }

tokio = { workspace = true }
byteorder = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
flate2 = { workspace = true }
snap = { workspace = true }

p384 = { version = "0.14.0-rc.8", features = ["ecdh", "ecdsa"] }
sha2 = "0.11.0"
aes = "0.9.0-rc.4"
ctr = "0.10.0-rc.4"
facet = "0.46"

raknet-tokio = { git = "https://github.com/bedrock-crustaceans/raknet.git" }

[dev-dependencies]
facet-json = "0.46"
