[package]
name = "bedrock_network"
version.workspace = true
edition.workspace = true

[features]
default = ["tokio"]
tokio = ["dep:tokio", "dep:raknet-tokio", "dep:futures-util"]
nethernet = ["dep:nethernet"]
nethernet-tokio = ["tokio", "nethernet", "dep:nethernet-tokio", "dep:bytes"]
test-util = ["tokio"]
v2193 = ["bedrock_protocol/v2193"]

[dependencies]
bedrock_protocol = { path = "../protocol" }
bedrock_protocol_core = { path = "../protocol_core" }
bedrock_auth = { path = "../auth" }

tokio = { workspace = true, optional = true }
byteorder.workspace = true
thiserror.workspace = true
rand.workspace = true
tracing.workspace = true
flate2.workspace = true
snap.workspace = true

p384 = { workspace = true, features = ["ecdh", "ecdsa"] }
sha2.workspace = true
aes = "0.9.3"
ctr = "0.10.1"
facet = "0.46"

nethernet = { git = "https://github.com/bedrock-crustaceans/nethernet", branch = "main", optional = true }
nethernet-tokio = { git = "https://github.com/bedrock-crustaceans/nethernet", branch = "main", optional = true }
futures-util = { version = "0.3", default-features = false, features = ["alloc"], optional = true }
bytes = { version = "1.12.1", optional = true }
raknet-tokio = { git = "https://github.com/bedrock-crustaceans/raknet.git", optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
facet-json = "0.46"
tempfile.workspace = true
