on: [ push, pull_request ]

name: Continuous integration

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: Test crates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
  
      - uses: Swatinem/rust-cache@v2
        with:
          add-job-id-key: false
          add-rust-environment-hash-key: false
          shared-key: "bedrock-rs-cache"
          cache-on-failure: false

      - name: Test all crates
        run: cargo test --all

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
  
      - uses: Swatinem/rust-cache@v2
        with:
          add-job-id-key: false
          add-rust-environment-hash-key: false
          shared-key: "bedrock-rs-cache"
          cache-on-failure: false

      - name: Test all crates
        run: cargo fmt --all -- --check

  clippy:
    name: Analyze with Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
  
      - uses: Swatinem/rust-cache@v2
        with:
          add-job-id-key: false
          add-rust-environment-hash-key: false
          shared-key: "bedrock-rs-cache"
          cache-on-failure: false

      - name: Test all crates
        run: cargo clippy --all
